# Make sure this is set to "kotlinforforge"
modLoader = "kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion = "[1.10,)" # Require at least 1.9.x
# License is REQUIRED after 1.16
license = 'LGPL'

[[mods]]
modId = "bpm"
version = "${file.jarVersion}"
displayName = "Blueprints"
credits = "James Raynor"
authors = "MrManiacc"
description = '''
A mod that basically allow for automation of anything
'''
[[dependencies.bpm]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.bpm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5]"
ordering = "NONE"
side = "BOTH"
